name: Main

on: [push, pull_request]

jobs:
  install-and-run-from-git:
    name: Test - Install & Run from Github

    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Install Node dependencies without building locally
        run: npm install --ignore-scripts

      # Prepare Test Environment

      - name: Create Dummy Package.json
        run: echo \{\} > test/package.json

      - name: Install Current Version as Git Dependency
        working-directory: test
        run: npm install ${{ github.repository }}#${{ github.sha }}

      - name: "Debug: List Dependency Folder Contents"
        working-directory: test
        run: find node_modules/userid -type f -print

      # Ensure the code works

      - name: Run Tests with Prepared Git Dependency
        run: npm test
        env:
          MOCHA_IMPORT_OVERRIDE: userid

  coverage:
    name: Generate - Coverage Reports
    runs-on: ubuntu-latest
    needs: [install-and-run-from-git]

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Install Lcov
        run: sudo apt-get install lcov -y

      - name: "Debug: Node version"
        run: node --version

      - name: Build
        run: npm install
        env:
          GENERATE_COVERAGE: "yes"

      - name: "Debug: List post build files"
        run: find * \( -path node_modules -o -path .git \) -prune -o -type f -print | tee /tmp/build.list

      - name: Test Coverage
        run: npm run coverage

      - name: "Debug: List post Coverage files"
        run: find * \( -path node_modules -o -path .git \) -prune -o -type f -print | tee /tmp/coverage.list

      - name: "Debug: Coverage diff"
        run: "diff -U 0 /tmp/build.list /tmp/coverage.list || :"

      - name: Gcov
        working-directory: build
        run: gcov -o Release/obj.target/userid/src/userid.o ../src/userid.cc

      - name: "Debug: List post Coverage files"
        run: find * \( -path node_modules -o -path .git \) -prune -o -type f -print | tee /tmp/gcov.list

      - name: "Debug: Gcov diff"
        run: "diff -U 0 /tmp/coverage.list /tmp/gcov.list || :"

      - name: Lcov Capture Gcov Data
        run: lcov --capture --directory . --output-file coverage/cc.info

      - name: Extract Our C++ Sources' Coverage Data
        run: lcov --extract coverage/cc.info '*.cc' --output-file coverage/cc.info

      - name: Combine Our C++ Sources' Coverage Data with JavaScript's Coverage Data
        run: lcov --add-tracefile coverage/cc.info --add-tracefile coverage/lcov.info --output-file coverage/lcov.info

      - name: "Debug: Print coverage report"
        run: lcov --list coverage/lcov.info

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish - Master
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [coverage, install-and-run-from-git]

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Create .npmrc with Auth Token
        run: echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc

      - name: Publish to npm
        run: "npm publish || :"
        env:
          NPM_TOKEN: ${{ secrets.npm_token }}
