name: Main

on: [push]

jobs:
  build-test-publish:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ '0.10', '0.12', 4, 5, 6, 7, 8, 9, 10, 11, 12, 13 ]

    runs-on: ${{ matrix.os }}

    name: Build Test on ${{ matrix.os }} with Node ${{ matrix.node }}

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Install Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Check Node version
        run: node --version

      - name: Build
        run: npm install

      - name: Test
        run: npm test
