name: Main

on: [push]

jobs:
  build-test-publish:
    name: Build Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Install Node 13
        uses: actions/setup-node@v1
        with:
          node-version: 13

      - name: Build
        run: npm install
