name: Update Dependencies, Test, and Commit

# Continuously update dependencies of this package and test with all versions of node on various OSes

on:
  # For self update development
  push:
    branches:
      - dev/self-update-deps

  # Every Saturday at 5:00am
  #schedule:
  #  - cron: 0 5 * * 6

jobs:
  update:
    runs-on: ubuntu-latest
    name: Update Dependencies
    steps:
      - name: Enable color for Npm output
        run: echo color = always >> .npmrc

      - name: Checkout latest code
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0

      - name: Install Node
        uses: actions/setup-node@v1

      - name: 'Debug: Node version'
        run: node --version

        # Update all dependencies

      - name: 'Update dependencies'
        run: npx npm-check-updates -u
        env:
          FORCE_COLOR: 1

        # Install dependencies and Build

      - name: Install dependencies and Build (using `npm install`)
        run: npm install

      - name: 'Info: Show differences'
        run: git diff --color=always

      - name: Clean touched but identical files
        run: git update-index --refresh

      - name: Test for changes (don't continue if there aren't any)
        id: changes
        run: '! git diff-index --quiet HEAD --'

      - name: Switch to update branch
        run: git checkout -b npm-check-updates

      - name: Add expected file changes
        run: git add package.json package-lock.json

      - name: 'Commit changes'
        run: git commit -m 'Automatic dependency update' --author="GitHub Actions <actions@github.com>"

      - name: Test for dangling changes (error!)
        run: git diff-index --quiet HEAD --

      - name: Push to GitHub
        run: git push origin npm-check-updates --force

  test-matrix:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        node: [10, 11, 12, 13, 14, 15] # There are problems on various architectures on lower versions that are more work to fix. Please open an issue if you need more version support

    runs-on: ${{ matrix.os }}

    needs: update

    name: Node ${{ matrix.node }} on ${{ matrix.os }}

    steps:
      - name: Enable color for Npm output
        run: echo color = always >> .npmrc

      - name: Checkout latest code
        uses: actions/checkout@v2
        with:
          ref: npm-check-updates

      - name: Install Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: 'Debug: Node version'
        run: node --version

        # Update all dependencies

      - name: 'Update dependencies'
        run: npx npm-check-updates -u
        env:
          FORCE_COLOR: 1

        # Install dependencies and Build

      - name: Install dependencies and Build (using `npm install`)
        run: npm install

      - name: 'Info: Show differences'
        run: git diff --color=always

        # Test long usernames on Linux

      - name: Add long username for test (only on Linux)
        if: runner.os == 'Linux'
        run: sudo useradd UsernameWithMoreThan15Chars

      - name: Add long groupname for test (only on Linux)
        if: runner.os == 'Linux'
        run: sudo useradd GroupnameWithMoreThan15Chars

      - name: Test Linux (with long names)
        run: npm test -- --color
        if: runner.os == 'Linux'
        env:
          LONG_USERNAME_TEST: UsernameWithMoreThan15Chars
          LONG_GROUPNAME_TEST: GroupnameWithMoreThan15Chars

        # Don't test long usernames on macOS

      - name: Test macOS (without long names)
        run: npm test -- --color
        if: runner.os == 'macOS'

  merge:
    name: 'Merge updates into master'

    needs: test-matrix

    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Merge
        run: git merge --ff-only npm-check-updates
      - name: Push
        run: git push origin master
