name: Test All Versions

on:
  push:
  pull_request:
  repository_dispatch:
  schedule:
    # Daily at 5:00am
    - cron: 0 5 * * *

jobs:
  test-matrix:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        node: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13] # Does not work on pre 1.0 versions.
        exclude:
          # excludes node 4/5 on macOS
          - os: macos-latest
            node: 4 # ../node_modules/node-addon-api/src/node_api.cc:15:10: fatal error: 'algorithm' file not found
          - os: macos-latest
            node: 5 # ../node_modules/node-addon-api/src/node_api.cc:15:10: fatal error: 'algorithm' file not found

    runs-on: ${{ matrix.os }}

    name: Node ${{ matrix.node }} on ${{ matrix.os }}

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Install Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: "Debug: Node version"
        run: node --version

      - name: Build
        run: npm install

      - name: Test
        run: npm test
        # Mocha does not work on 4/5
        if: matrix.node >= 6
