name: Test All Versions

on:
  push:
  pull_request:
  repository_dispatch:
  schedule:
    # Daily at 5:00am
    - cron: 0 5 * * *

jobs:
  test-matrix:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        node: [6, 7, 8, 9, 10, 11, 12, 13, 14, 15] # There are problems on various architectures on lower versions that are more work to fix. Please open an issue if you need more version support

    runs-on: ${{ matrix.os }}

    name: Node ${{ matrix.node }} on ${{ matrix.os }}

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Install Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: 'Debug: Node version'
        run: node --version

      - name: Build
        run: npm ci

      - name: Add long username for test
        run: sudo useradd UsernameWithMoreThan15Chars

      - name: Add long groupname for test
        run: sudo useradd GroupnameWithMoreThan15Chars

      - name: Test
        run: npm test
        # Mocha does not work on 4/5
        if: matrix.node >= 6
        env:
          LONG_USERNAME_TEST: UsernameWithMoreThan15Chars
          LONG_GROUPNAME_TEST: GroupnameWithMoreThan15Chars
